### ISSUE TITLE
Всё должно работать!

### ISSUE THREAD

**Issue by makarov-mv** [burunduk3/lksh-2015-winter-as-agar#1]
Ничё не работает! Исправить!

**Comment by Noobgam** [comment]
Прикрепите логи сервера, пожалуйста.

**Comment by vasalf** [comment]
логи? какие логи?

**Comment by vasalf** [comment]
у нас есть логи?

**Comment by Noobgam** [comment]
Ну что-то то не работает. Вроде, я умею отлавливать эксэпшны некоторые и принтить ошибки, которые нужно игнорировать

**Comment by vasalf** [comment]
Noobgam, не работает ничего и это вполне ожидаемо

**Comment by Noobgam** [comment]
Окей, прочитал код, понял. Сейчас переделаю.
